export const ENDPOINTS = {
  HEALTH: '/health',
  AUTH: {
    LOGIN: '/auth/login',
    ME: '/auth/me',
    OPTIONS: '/auth/options',
    CHANGE_PASSWORD: '/auth/change-password',
    ADMINS: '/auth/admins',
    ADMIN_DELETE: (key) => `/auth/admins/${encodeURIComponent(key)}`,
  },
  SCHEDULES: {
    LIST: '/schedules',
    CREATE: '/schedules',
    DETAIL: (id) => `/schedules/${encodeURIComponent(id)}`,
    UPDATE: (id) => `/schedules/${encodeURIComponent(id)}`,
    DELETE: (id) => `/schedules/${encodeURIComponent(id)}`,
  },
  ROOMS: {
    LIST: '/rooms',
    CREATE: '/rooms',
    AVAILABLE: '/rooms/available',
    DETAIL: (roomNumber) => `/rooms/${encodeURIComponent(roomNumber)}/full`,
    UPDATE: (id) => `/rooms/${encodeURIComponent(id)}`,
    DELETE: (id) => `/rooms/${encodeURIComponent(id)}`,
    BOOKINGS: (roomNumber) => `/rooms/${encodeURIComponent(roomNumber)}/bookings`,
    BOOK: (roomNumber) => `/rooms/${encodeURIComponent(roomNumber)}/bookings`,
    CANCEL_BOOKING: (bookingId) => `/bookings/${encodeURIComponent(bookingId)}`,
  },
  EVENTS: {
    LIST: '/events',
    CREATE: '/events',
    DETAIL: (id) => `/events/${encodeURIComponent(id)}`,
    UPDATE: (id) => `/events/${encodeURIComponent(id)}`,
    DELETE: (id) => `/events/${encodeURIComponent(id)}`,
    REGISTRATIONS: (id) => `/events/${encodeURIComponent(id)}/registrations`,
    REGISTER: (id) => `/events/${encodeURIComponent(id)}/registrations`,
    CANCEL_REGISTRATION: (id, studentId) => `/events/${encodeURIComponent(id)}/registrations/${encodeURIComponent(studentId)}`,
  },
  ANNOUNCEMENTS: {
    LIST: '/announcements',
    CREATE: '/announcements',
    DETAIL: (id) => `/announcements/${encodeURIComponent(id)}`,
    UPDATE: (id) => `/announcements/${encodeURIComponent(id)}`,
    DELETE: (id) => `/announcements/${encodeURIComponent(id)}`,
  },
  ASSIGNMENTS: {
    LIST: '/assignments',
    CREATE: '/assignments',
    DETAIL: (id) => `/assignments/${encodeURIComponent(id)}`,
    UPDATE: (id) => `/assignments/${encodeURIComponent(id)}`,
    DELETE: (id) => `/assignments/${encodeURIComponent(id)}`,
  },
  AGENT_CONFIG: {
    GET: '/agent-config',
    UPDATE: '/agent-config',
  },
  STATS: '/stats',
  CHAT: {
    SEND: '/chat',
  },
};
