import {
  LayoutDashboard,
  CalendarDays,
  DoorOpen,
  Sparkles,
  Megaphone,
  BookOpenCheck,
  Settings,
} from 'lucide-react';

export const NAV_ITEMS = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    shortLabel: 'Hub',
    description: 'Overview & quick schedule',
    icon: LayoutDashboard,
    countKey: null,
  },
  {
    id: 'schedules',
    label: 'Timetable Routine',
    shortLabel: 'Routine',
    description: 'Weekly timetable & classes',
    icon: CalendarDays,
    countKey: 'schedules',
  },
  {
    id: 'rooms',
    label: 'Rooms & Bookings',
    shortLabel: 'Rooms',
    description: 'Facility availability & reservations',
    icon: DoorOpen,
    countKey: 'rooms',
  },
  {
    id: 'events',
    label: 'Events & RSVP',
    shortLabel: 'Events',
    description: 'Workshops & campus sessions',
    icon: Sparkles,
    countKey: 'events',
  },
  {
    id: 'announcements',
    label: 'Notices & Circulars',
    shortLabel: 'Notices',
    description: 'High priority notices & updates',
    icon: Megaphone,
    countKey: 'announcements',
  },
  {
    id: 'assignments',
    label: 'Tasks & Deadlines',
    shortLabel: 'Tasks',
    description: 'Submissions & pending coursework',
    icon: BookOpenCheck,
    countKey: 'assignments',
  },
  {
    id: 'agent-config',
    label: 'AI Agent Settings',
    shortLabel: 'AI Config',
    description: 'System prompt & model parameters',
    icon: Settings,
    countKey: null,
    adminOnly: true,
  },
];
